### ISSUE TITLE
How to use this extension to integarte with Twilio API for 2FA OTP

### ISSUE THREAD

**Issue by ganesh2183** [Hannah-PortSwigger/TOTPAuthenticate#2]
Is there anyway to use this extension with twilio 2FA OTP in burp suite professional for authenticated scan.

**Comment by Hannah-PortSwigger** [comment]
Apologies for the late response. If you're using Burp Suite Professional, I'd recommend using the BApp Store extension, [Google Authenticator](https://portswigger.net/bappstore/fb3685f958f8424493945c6c60c0920c) over this extension. This extension is more difficult to configure, as it is designed to be used with Burp Suite Enterprise Edition.
