### ISSUE TITLE
No license file present

### ISSUE THREAD

**Issue by kwwall** [Hannah-PortSwigger/TOTPAuthenticate#3]
Simple ask... presumably you intended to release this as open source.

So, could you please pick an [approved open source license](https://opensource.org/licenses/) and document that in a new **LICENSE.md** file, or if not there, note it in a prominent place in your **README.md** file?

If you don't have a clear license, then you will get lots of people not considering this. Thanks in advance.

**Comment by Hannah-PortSwigger** [comment]
Hi

Thanks for raising this. I've added a license file to this extension.

If there's anything else I can help with, then please let me know.
